# - name: ping the server
#   hosts: web
#   tasks:
#   - name: ping the server
#     ansible.builtin.ping:

- name: ping the server
  hosts: ansible
  tasks:
  - name: ping the server
    ansible.builtin.ping:


  